version: "3.9"
services:
  database:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5678:5432"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d/
      - data:/var/lib/postgresql/data
    networks:
      - default
  api:
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - api:/app/cmd/ghost/_storage
    networks:
      - default
volumes:
  data:
  api:
